### ISSUE TITLE
syntax highlight

### ISSUE THREAD

**Issue by ctf0** [suryatech/codeschool-shaping-up-with-angular#1]
hi there ,many thanx for this series ,one question though

the below img is from the `Tabs Inside Out`
![hl](https://cloud.githubusercontent.com/assets/7388088/5976551/ee59f7c6-a897-11e4-883b-db88a9a21806.jpg)

could u plz tell me which editor/IDE u were using ?

**Comment by suryatech** [comment]
I was using Sublime Text 2. Hope that helps.

**Comment by ctf0** [comment]
can u tell me which scheme u were using ? ,am trying to implement the same thing but i cant find any scheme/syntax lang that have this scopes.

**Comment by suryatech** [comment]
I am not sure what you mean by scheme/syntax lang. Can you please elaborate?

Sorry for the delay though.

**Comment by ctf0** [comment]
the scheme is the color scheme file u use to get the highlight like `monokai` 
the syntax language is the actual language u use in ST like `html,js,css,etc..` ,
and so i was asking were u using a custom package other than the default that came with ST ?

**Comment by suryatech** [comment]
Nothing really fancy and I don't think I had anything apart from the popular Angular plugins like AngularJS/ AngularJS Snippets.

Hope that helps.

**Comment by ctf0** [comment]
unfortunately i cant get the same highlighting as in the screenshot because anything within the double quotes are treated the same so all get the same color which is driving me nuts ,still thanx for ur help :+1: .
